baseURL = 'https://www.dva-art.com/'
languageCode = 'en-us'
title = 'DVArt, Sharing the wonder of nature one image at a time'
theme = 'dva'
 
 enableRobotsTXT = true


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

    [markup.goldmark.renderer]
     hardWraps = true

[services]
  [services.googleAnalytics]
    ID = 'G-7KGVY0SXZM'

[Params.social.share]
  facebook = true
  twitter = true
  email = true

  [params]
  Description = "Sharing the wonders of the natural world one image at a time.  A photographer and visual artist living in wonderful New Zealand"
  Twitter_Image = "/imgs/DVArt.svg"
